### ISSUE TITLE
directives ngInclude and parallaxBackground $compile error

### ISSUE THREAD

**Issue by mrbatista** [brettdonohoo/angular-parallax#18]
If use parallaxBackground with ngIncude directive I have compile error:
Error: [$compile:multidir] Multiple directives [ngInclude, parallaxBackground] asking for transclusion on:....

It's a bug or parallaxBackground is incompatible directive with ngInclude?

Best regards

**Comment by brettdonohoo** [comment]
Hi Matteo.

If possible, would you recreate your issue on Plunker <http://plnkr.co/> or
somewhere else live so I can take a look?

Thanks.

Brett

**Comment by mrbatista** [comment]
I have create [this](http://plnkr.co/edit/Cuf5VHVeEZaIgShHrPDT) Plunker that recreate issue.

**Comment by brettdonohoo** [comment]
Maybe try something like this
<http://plnkr.co/edit/Lp9owRCxS1zpsJlfs3Zt?p=info>?

http://stackoverflow.com/questions/27456294/angular-directive-asking-for-transclusion

**Comment by mrbatista** [comment]
Resolved with your example. Thanks!
